### ISSUE TITLE
Still no luck on suspended sleep + wake?

### ISSUE THREAD

**Issue by FennekFox19** [AdhamNasr/MacBookAir-ArchLinux-i3#6]
Read title

**Comment by AdhamNasr** [comment]
My current setup works, but not the best experience tbh, that's why I didn't add it to the guide.

I will update some parts of the guide in the coming month.

If there is anything you'd like me to consider adding, or would like to add something yourself, comment it here so that we can further discuss it before the next update.

Things I'm thinking of adding:
- Podman
- Cockpit
- Change boot splash
- Edit console login (inspired by https://medium.com/@reefland/replace-the-linux-console-login-with-something-different-ad08ba192dd8)

As much as these updates might be leaning towards servers, I won't be using Podman for heavy stuff, and I mostly use the terminal on that machine (hence why there is no login screen).

Edit: 
- I'm also considering writing a bash script to automate the whole installation.
- Also the 'bcwc-pcie-git' package is no longer in the AUR.
